"""added notes table and join it to contact table

Revision ID: 1a997dc5f6e9
Revises: e8a926f8f2aa
Create Date: 2024-06-26 11:18:54.402605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a997dc5f6e9'
down_revision = 'e8a926f8f2aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.VARCHAR(length=500), nullable=True))

    # ### end Alembic commands ###
