"""removed nullable constraint

Revision ID: 5241126de042
Revises: 1a997dc5f6e9
Create Date: 2024-06-27 15:29:30.892232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5241126de042'
down_revision = '1a997dc5f6e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('contact_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('contact_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
