"""added nullable contraint on contact_id

Revision ID: aa9d583a3b83
Revises: 5241126de042
Create Date: 2024-06-27 15:35:32.998316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa9d583a3b83'
down_revision = '5241126de042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('contact_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('contact_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
