"""adding new column notes

Revision ID: e8a926f8f2aa
Revises: 45c8a22abfd8
Create Date: 2024-06-26 10:34:30.648249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8a926f8f2aa'
down_revision = '45c8a22abfd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_column('notes')

    op.create_table('note',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('contact_id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.VARCHAR(length=500), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
